services:
  wizard:
    build:
      dockerfile: Dockerfile.wizard
    ports:
      - "3300:3300"
    networks:
          - adapter-network
  client-2:
    build:
      dockerfile: Dockerfile.client2
    networks:
      - adapter-network

  client-1:
    build:
      dockerfile: Dockerfile.client1
    networks:
      - adapter-network

  server-1:
    build:
      dockerfile: Dockerfile.server1
    networks:
      - adapter-network

networks:
  adapter-network:
    driver: bridge
